 apiVersion: networking.k8s.io/v1beta1
 kind: Ingress
 metadata:
   name: myingressresource
 spec:
   rules:
   - http:
      paths:
      - path: /*
        backend:
          serviceName: flask-app
          servicePort: 5000
   - host: python.34-121-245-138.nip.io   